### ISSUE TITLE
Log level not being honored

### ISSUE THREAD

**Issue by christopher-francisco** [pact-foundation/pact-js-core#109]
I see `WARN` and `INFO` logs even when I set it to `error`:

```javascript
const { Verifier } = require('@pact-foundation/pact');
const pact = require('@pact-foundation/pact-node');

pact.logLevel('error');

...

return new Verifier().verifyProvider(opts);
```

Here are the logs:

```
    WARN: Ignoring unsupported matching rules {"min"=>1} for path $['body']['resource']

    WARN: Ignoring unsupported matching rules {"min"=>1} for path $['body']['resource']

    /home-folder/node_modules/@pact-foundation/pact/node_modules/@pact-foundation/pact-node/standalone/darwin-1.44.1/lib/vendor/ruby/2.2.0/gems/pact-support-1.6.1/lib/pact/term.rb:30: warning: character class has '-' without escape: /https?:\/\/[0-9a-zA-Z-.]+/

    WARN: Ignoring unsupported matching rules {"min"=>1} for path $['body']['resource']

    INFO: Reading pact at <my url>
```

**Comment by mefellows** [comment]
Thanks Chris, we have some work to do as there are multiple layers where logging is set. This setting doesn't propagate all the way through in older versions of pact, but also to my knowledge we can't set log-level on the verification process (which is external to the node/JS libs).

@bethesque thoughts? I can raise a feature request for this.

**Comment by bethesque** [comment]
I thought I'd done it in the verifier, but it seems I've only done it for the mock service https://github.com/pact-foundation/pact-mock_service/blob/master/lib/pact/mock_service/logger.rb

Easily added, raise an issue.

**Comment by bethesque** [comment]
But really, I'm trying to fix all those warnings so you don't need to change the log level. The latest version of pact-js shouldn't have them. If it does, please let me know.

**Comment by mefellows** [comment]
Created https://github.com/pact-foundation/pact-provider-verifier/issues/26 to track issue.

**Comment by mefellows** [comment]
Closing as fixed.
