### ISSUE TITLE
pact_binary_location to be defined as a parameter in .npmrc

### ISSUE THREAD

**Issue by renukhush** [pact-foundation/pact-js-core#213]
We are using pact behind a corporate firewall. In view of #88, when downloading the following

Downloading Pact Standalone Binary v1.81.0 for platform darwin from https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.81.0/pact-1.81.0-osx.tar.gz

we are having issue.

Similar when downloading for node-sass pacakge,  
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node

it allows you set the download site. in .npmrc file 
sass_binary_site=http://localhost:8081/artifactory/for-node-sass

I know we can update. the package.json

"config": {
    "pact_binary_location": "https://artifactory.ourcompany.com.au/artifactory/pact-github-repo/download/v1.81.0/"
  },

but it would be more convenient to have. it as a parameter. in. package.json

**Comment by mefellows** [comment]
> but it would be more convenient to have. it as a parameter. in. package.json

Do you mean in the `.npmrc` file? It is already a parameter in `package.json`.

Why is it more convenient? Can you please elaborate? I'm reluctant to make this process more complicated than it already is without good reason to.

**Comment by renukhush** [comment]
Hi 
Sorry I meant it to be in .npmrc file.
The reason is that .npmrc file is common across all environments (dev,test,non-prod. and prod) so when the npm. install is carried out in any environment, the pact_binary_location been defined in .npmrc the npm install and. postinstall runs seamlessly without a need to modify the package.json

**Comment by mefellows** [comment]
Cool, thanks for elaborating.

I'm happy to support the feature as a PR, but don't have time to currently implement it. I've marked it as good and ready for somebody to pick up.

**Comment by renukhush** [comment]
Thanks @mefellows

**Comment by mefellows** [comment]
Closing as no longer relevant with latest version.

**Comment by cjperusse** [comment]
> Closing as no longer relevant with latest version.

What does this even mean? Can you provide details as what is provided in place of this in the "latest version" (what version is the latest version?)

**Comment by mefellows** [comment]
Would you like to try that again, this time with manners?
