### ISSUE TITLE
Chore: Prevent npm publish when node envs other than 12 fail

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js-core#216]
Currently, travis runs npm publish when a tagged linux build passes on node 12.
This is a potential problem if the node 12 build passes, but other node envs fail, resulting in a potentially broken package being published. 

We should use something like https://docs.travis-ci.com/user/build-stages to prevent publishing if not all environments pass the build.

Ideally, we would also wait on success from the windows builds (currently run by appveyor) too. I'm not sure how practical that is, though.

**Comment by mefellows** [comment]
We now have a separate release stage from build. Closing.
