### ISSUE TITLE
Rename pact-node

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-js-core#224]
See https://github.com/pact-foundation/pact-node/issues/145 and other conversations.

Candidate names:

* pact-cli

Reasons not to do this:

* Impact to the ecosystem (as at today, there are 1.1k known uses on Github - this could break a a lot of things)
* We're deprecating it over time in favour of Rust, so why go through this pain
* Renaming in may not actually help the confusion

**Comment by TimothyJones** [comment]
We've renamed pact-node to pact-core (and the repo to pact-js-core) for the upcoming new release of pact-js (currently in beta). This will break pact-karma, see [here](https://github.com/pact-foundation/pact-js/issues/626) for a discussion.
