### ISSUE TITLE
Pact-node's ruby bindings don't work if the project name has spaces

### ISSUE THREAD

**Issue by christopher-francisco** [pact-foundation/pact-js-core#247]
## Software versions

* **OS**: `macOS 10.13.3`, `Centos 7 (probably)`
* **Consumer Pact library**: `5.9.1`
* **Node Version**: `8`

## Expected behaviour

It shouldn't matter whether the directory name has or hasn't spaces on its name.

## Actual behaviour

When creating the mock server, it somehow split the project path where spaces exist: `/var/lib/jenkins/workspace/My Cool App/`, and attempts to run `Cool` as a command. It then, of course, fails saying 

```
/node_modules/@pact-foundation/pact-node/standalone/darwin-1.43.1/lib/ruby/bin/ruby: line 14: Cool: command not found
```

## Steps to reproduce

1. Change the name of your app to something with spaces (if possible with 3 words), like: `my-cool-app` to `My Cool App`.
2. Run the PactJS tests.

**Comment by mefellows** [comment]
Closing as latest version removes Ruby core.
