### ISSUE TITLE
Remove request as a dependency

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js-core#259]
We have a dependency on https://www.npmjs.com/package/request , which is deprecated (and has been for some time).

To avoid everyone getting a warning, let's remove it.

I suggest replacing it with `axios`, but I have no strong opinion on it. I also haven't yet done a review of where we're using it.

**Comment by mefellows** [comment]
Looks like we use it in the installer to download the ruby binaries dynamically, and in the service code to check if the Ruby Mock Service is up and running.

Axios is close enough to a default choice, and the project seems to have steered itself out of the wilderness, so is a safe enough choice I think.

**Comment by adambocco** [comment]
Hello, 
I'd like to work on this issue. It looks like just the two places @mefellows mentions in src/service.ts and standalone/install.ts. 
Thanks

**Comment by mefellows** [comment]
Amazing - thanks @adambocco .

I think @TimothyJones has made some progress/thinking on this. Tim - anything worth sharing?

If you're not already, please join slack.pact.io (and join the #pact-js-development channel) and we can chat there if you run into issues

**Comment by TimothyJones** [comment]
Yes please, that would be excellent!

I took a stab at it before dinner yesterday, and found it a bit annoying to give proxy details to axios. It’s definitely possible, but might be more convenient to use a different library. I didn’t have anything worth saving- all I discovered is “this is more than 10 mins”.

Implementation wise and library choice, it’s up to you. I’d be happy to see any PR resolving the deprecation warnings

**Comment by TimothyJones** [comment]
@adambocco Did you get anywhere with this? We're about to touch the installer code for a different reason, so if you have any work towards the solution it would be the perfect time to get it in.
