### ISSUE TITLE
Breaking changes for next release

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js-core#263]
I'm going to track some breaking changes that would be worth making in the next release:

[] Remove `verbose`, since it is now implied by `logLevel: DEBUG` (make sure we check that this can be set in pact-js for each constructor that supports it before doing this).

[] Remove all deprecated options

[] Remove qPromise library

**Comment by TimothyJones** [comment]
Deprecated options have been removed in 95b88e084bf66d97717a99ac4ebf800c8116bc68

**Comment by mefellows** [comment]
Thanks Tim!

**Comment by mefellows** [comment]
(I love seeing a red diff!)

**Comment by TimothyJones** [comment]
`qPromise` has been removed in a5076cc974c052ab9d281c86d90c136ea00f0f84.

I didn't remove the verbose - not everywhere it is set has the `logLevel` option, so it felt like a bit more thinking was required.

Releasing v11 now.
