### ISSUE TITLE
OpenSSL::SSL::SSLError while using LetsEncrypt ssl certificates

### ISSUE THREAD

**Issue by MishaTsypkin** [pact-foundation/pact-js-core#333]
### Software versions

- **OS**: _Ubuntu 20.04_
- **Consumer Pact library**:9.16.2
- **Provider Pact library**: 2.74.1
- **Node Version**: v12.15.0
### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code and have [read](https://github.com/pact-foundation/pact-js/#test-fails-when-it-should-pass) the section on intermittent test failures
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproducable git repository (see below) to illustrate the problem

### Expected behavior

The client should establish an HTTPS connection to the Pact Broker

### Actual behavior

Client fails to verify SSL certificates

### Steps to reproduce

1. Run a pact broker with LetsEncrypt SSL certificates
2. Use `@pact-foundation/pact` library to establish an HTTPS connection with Pact broker.

### Details

It seems that pact is using [Ruby HTTP client](https://github.com/nahi/httpclient) under the hood, which is reported for having [outdated SSL certificate files bundled inside the library](https://github.com/nahi/httpclient/issues/445).
In the [httpclient issue](https://github.com/nahi/httpclient/issues/445), it is recommended to monkey patch HTTP client library to use system default SSL certificates.

**Comment by mefellows** [comment]
Please update, we released a version earlier this evening to fix this bug - can you please confirm if it fixes your problem?

**Comment by MishaTsypkin** [comment]
v9.16.3, it is still failing for my case:
```
    "@pact-foundation/pact": "9.16.3",
    "@pact-foundation/pact-node": "10.13.8"
```
Output:
```
$ NODE_ENV=test jest --config=jest.provider.cdc.config.js --runInBand
[2021-10-01 12:40:44.170 +0000] WARN (248 on 1523dc979738): pact-node@10.13.8: 'consumerVersionTag' and 'providerVersionTag' have been deprecated, please use 'consumerVersionTags' or 'providerVersionTags' instead
 FAIL  src/__tests__/pact/provider/platform.provider.cdc.ts (17.843s)
  Platform cdc
    ✕ should verify the contract (11553ms)

  ● Platform cdc › should verify the contract

    Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: certificate verify failed , attempt 1 of 3

    Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: certificate verify failed , attempt 2 of 3

    Error making request - OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: certificate verify failed , attempt 3 of 3
    ```

**Comment by mefellows** [comment]
I've just checked that it supports allowing disabling of the certificate as per https://github.com/pact-foundation/pact-ruby-standalone/issues/69#issuecomment-931889061, but it should also support the OpenSSL standard SSL_CERT_FILE or SSL_CERT_DIR env vars.

See also the upstream ticket: https://github.com/pact-foundation/pact-ruby-standalone/issues/69.

**Comment by mefellows** [comment]
@TimothyJones going to pin this issue whilst we sort the situation out.

**Comment by MishaTsypkin** [comment]
Finally made it work with `SSL_CERT_FILE`.
If anyone is still facing this issue - keep in mind that SSL certificates on your machine (or in CI image) might be outdated too.
You can download the latest certificates from [the Mozilla repo](https://curl.se/docs/caextract.html) in order to test it.

Thanks a lot @mefellows for the support!

**Comment by mefellows** [comment]
Thank you for confirming Misha!

**Comment by mefellows** [comment]
`v10.13.9` is now released with upstream fix - can you please check if this resolves the issue? You should no longer need to set environment variables manually.

**Comment by MishaTsypkin** [comment]
It looks like this is not yet available in the latest version of the client library `pact-foundation/pact`, but when I do:
```
  "resolutions": {
    "@pact-foundation/pact-node": "^10.13.9"
  }
```
It works like a charm! Thanks a lot @mefellows :pray:

**Comment by mefellows** [comment]
Great, thanks for clarifying!

A clean install should bring in the right version, we only pin to the major version: https://github.com/pact-foundation/pact-js/blob/4c949aec080472ea18d883468e705918a5389430/package.json#L97
