### ISSUE TITLE
Support for BuildUrl in publisher

### ISSUE THREAD

**Issue by konalegi** [pact-foundation/pact-js-core#352]
### Checklist

Before making a feature request, I have: 

- [x] [Searched the issues to check that this feature hasn't been requested before](https://github.com/pact-foundation/pact-js-core/issues?q=is%3Aissue)
- [x] Checked the documentation to see if it is possible to do what I want already 

### Feature description

the publish method in pact broker CLI support BUILD_URL, do you have plans to include this option in this library?
https://github.com/pact-foundation/pact_broker-client/blob/master/lib/pact_broker/client/cli/broker.rb#L33

### Use case

We want to enable tracing of the related CI builds in our logging system (some dashboard where people can enter build URL and it will output all related builds) so that people do need to manually search for provider build in case of any failures. To do so we need to pass the build URL during contract publish to the provider build, everything is already in pact-broker, pact-broker-cli but missing support in js library. 

Thanks

**Comment by mefellows** [comment]
Thanks. We would be happy to accept a PR for this.

It's worth noting that our recommended approach is to use the CLI directly, but we're not dropping support for this any time soon.

**Comment by konalegi** [comment]
@mefellows I've created simple PR to add buildUrl, please take a look when you have time.

**Comment by mefellows** [comment]
Looks like this is released, thanks for your contribution!
