### ISSUE TITLE
Add branch support for publishPacts

### ISSUE THREAD

**Issue by flappyBug** [pact-foundation/pact-js-core#354]
### Checklist

Before making a feature request, I have: 

- [x] [Searched the issues to check that this feature hasn't been requested before](https://github.com/pact-foundation/pact-js-core/issues?q=is%3Aissue)
- [x] Checked the documentation to see if it is possible to do what I want already 

### Feature description

As described in the [pact documentation](https://docs.pact.io/pact_broker/branches/#when-are-branches-created), we're using branch to replace tag. But I can't find how to set branch options when using `publishPacts`

**Comment by TimothyJones** [comment]
All of the pact broker commands listed there should work in your npm script:

```
"pact:publish": "pact-broker publish ./pacts --consumer-app-version $(however-you-get-your-version) --branch $(however-you-get-your-branch)"
```

**Comment by flappyBug** [comment]
Thanks for your reply. Though this may works, it can be hard to setup cli for both local machine and CI. So I still prefer there is an option to set branch version for `publishPacts`

**Comment by TimothyJones** [comment]
The CLI is exposed to npm by pact-js on install- you don’t have to do anything special to use it (if you want to use it outside an npm script, you can use npx)

**Comment by TimothyJones** [comment]
See the documentation here: https://github.com/pact-foundation/pact-js#publish-in-npm-scripts

(Of course, you're quite right that the API doesn't support the branch options, and should).

**Comment by flappyBug** [comment]
Thanks @TimothyJones . I think I can contribute on adding the branch option if it's reasonable.

**Comment by TimothyJones** [comment]
That would be very welcome, yes please.

At the moment, pact-node is a branch (pact-node). I’m happy to cherry-pick it across after you make the PR, though.

**Comment by roshanjohn** [comment]
Hi guys. I can see the PR changes are not available on master yet. Can you help out?

+ @mefellows

**Comment by mefellows** [comment]
We'd happily accept a PR, but I also strongly suggest you use the CLI. I'm likely to deprecate this class in a future major release.

**Comment by TimothyJones** [comment]
I think what @roshanjohn is saying is that the changes are in pact-node but not master

**Comment by TimothyJones** [comment]
The PR is above, #355
