### ISSUE TITLE
Windows Issues::Enable Long Path 

### ISSUE THREAD

**Issue by akanksha-centric** [pact-foundation/pact-js-core#358]
I have tried with solution provided on this (https://github.com/pact-foundation/pact-js-core#windows-issues)  but still I am not able to execute  with long path however it perfectly working if I short the path,  I have attached the images of an issues for your reference.

#101 

<img width="725" alt="image" src="https://user-images.githubusercontent.com/96420157/151755718-bfd19b5c-23d7-463e-ade6-705cacebdfff.png">

**Comment by TimothyJones** [comment]
Apologies, we should probably remove that section from the documentation (long path support is enabled by default in current versions of windows).

Otherwise, unfortunately this is an upstream issue for us. It will be cleared when the Rust-based core of pact is used.

If you are unable to use a shorter path, you could try the beta version of the next release of pact, but the interface and binaries are currently a little unstable.

**Comment by akanksha-centric** [comment]
@TimothyJones  I have rechecked it by reducing the file path length it successfully executed if length is less than equal to 46 of path length is greater then 46 it throw an error after executing provider. here I am pasting the exact error so that you can provide me a solution for it.

**1) Contact account API Pact verification
       validates the expectations of Matching Service:
     Error: C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.36.1/lib/pact/provider_verifier/app.rb:4:in `require': cannot load such file -- pact/provider_verifier/provider_states/remove_provider_states_header_middleware (LoadError)        
        from C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.36.1/lib/pact/provider_verifier/app.rb:4:in `<top (required)>'

        from C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.36.1/lib/pact/provider_verifier/cli/verify.rb:45:in `require'
        from C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.36.1/lib/pact/provider_verifier/cli/verify.rb:45:in `verify'
        from C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/vendor/ruby/2.2.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.36.1/lib/pact/provider_verifier/cli/custom_thor.rb:17:in 
`start'
        from C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/app/pact-provider-verifier.rb:33:in `<main>'

      at ChildProcess.<anonymous> (node_modules\@pact-foundation\pact-node\src\verifier.js:185:64)
      at Object.onceWrapper (node:events:510:26)
      at ChildProcess.emit (node:events:402:35)
      at ChildProcess.cp.emit (node_modules\cross-spawn\lib\enoent.js:34:29)
      at maybeClose (node:internal/child_process:1064:16)
      at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)**

**Comment by mefellows** [comment]
Yes, apologies for the confusion, as stated it's an issue in the current version.

You might like to try the latest beta (https://github.com/pact-foundation/pact-js#pact-js-v3), with the usual warnings around it being a beta

**Comment by TimothyJones** [comment]
> less than equal to 46 of path length is greater then 46

So, this is the base path. Unfortunately, due to the way the tooling of the binary works, the full path length it fails on is much longer. From your error message it is failing on the following 263 character path: `C:/CmiCode/JarusScrum/ContractTest/ContractConfig/node_modules/@pact-foundation/pact-node/standalone/win32-1.88.80/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.36.1/lib/pact/provider_verifier/provider_states/remove_provider_states_header_middleware.rb`

**Comment by mefellows** [comment]
I'm going to close this issue as the latest version (13.x.x) has removed this issue. We won't be able to fix this is previous versions.
