### ISSUE TITLE
[ci] - windows builds are failing in CI

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-js-core#365]
see build [here](https://github.com/pact-foundation/pact-js-core/runs/5546996030?check_suite_focus=true) for example

Tries to install node-gyp and then just complains that nothing is found `bash **script/ci/build-and-test.sh**`

Appears to have started at least 22 days ago 

```
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\[20](https://github.com/pact-foundation/pact-js-core/runs/5546996030?check_suite_focus=true#step:4:20)22\Enterprise"

**Comment by mefellows** [comment]
I recently fixed this issue in the Node JS. The default node gyp that ships with npm is super old and isn't compatible with recent visual studios.

Just tested a fix: https://github.com/pact-foundation/pact-js-core/runs/5599252610?check_suite_focus=true
