### ISSUE TITLE
[ci] - scripts folder containing release/ci files (in a common format across repos) is called script in this repo

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-js-core#366]
The folder containing the ci and release scripts is called `script` here but `scripts` in other repos. we should standardise 👍🏾 

- Current releasing docs in this repo refer to `scripts` folder.
- doesn't match up with other repos

**Comment by mefellows** [comment]
Good idea. I'll fix in the node-gyp branch which will replace the mainline.

**Comment by YOU54F** [comment]
so its called script in lots of others repos like this one https://github.com/pact-foundation/pact-broker-docker so its probably fine
