### ISSUE TITLE
pact-node has deprecated dependency warnings

### ISSUE THREAD

**Issue by TimothyJones** [pact-foundation/pact-js-core#374]
### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: Irrelevant
- **Pact Node version**: @pact-foundation/pact-node@10.17.2
- **Node Version**: `v14.17.3`

### Issue Checklist

Please confirm the following:

- [X] I have upgraded to the latest
- [X] I have the read the FAQs in the Readme
- [X] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

`npm install` of the current release doesn't have any deprecated package warnings

### Actual behaviour

```
$ npm install @pact-foundation/pact-node@10.17.2
npm WARN deprecated libnpmconfig@1.2.1: This module is not used anymore. npm config is parsed by npm itself and by @npmcli/config
```

Probably can be fixed by removing libnpmconfig and using the other package (or environment variables, maybe? I don't know what the official pattern is).

**Comment by mefellows** [comment]
This package has been removed in the latest version. I'm not sure of the value of backporting a fix to the previous major version - what do you think?

**Comment by TimothyJones** [comment]
Personally, I wouldn't release any more 9.x versions- unless there's an expectation that people won't be able to upgrade.

**Comment by mefellows** [comment]
Cool, thanks Tim. I think so too.
