### ISSUE TITLE
Error while installing binary: Checksum rejected for file 'pact-1.88.77-osx.tar.gz' with checksum pact-1.88.77-osx.tar.gz.checksum

### ISSUE THREAD

**Issue by avinashs2401** [pact-foundation/pact-js-core#376]
### Software versions

- **OS**: MacOS Catalina 10.15.7
- **Pact Node version**: 10.13.10
- **Node Version**: 14.15.1
- **Other Versions**: 
     Angular 11
    "@pact-foundation/karma-pact": "^3.1.0",
    "@pact-foundation/pact-node": "^10.13.10",
    "@pact-foundation/pact-web": "~9.16.0",

### Issue Checklist

Please confirm the following:

- [x] I have upgraded to the latest
- [x] I have the read the FAQs in the Readme
- [x] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

Should install packages properly and successfully complete `npm install`

### Actual behaviour

`Error: Error while installing binary: Checksum rejected for file 'pact-1.88.77-osx.tar.gz' with checksum pact-1.88.77-osx.tar.gz.checksum`

### Steps to reproduce

- `npm install`

### Relevant log files

_Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link to a gist)._

```
Extracting binary from xxx/node_modules/@pact-foundation/pact-node/standalone/pact-1.88.77-osx.tar.gz.
Error: Error while installing binary: Postinstalled Failed Unexpectedly: Error: Error while installing binary: Extraction failed for xxx/node_modules/@pact-foundation/pact-node/standalone/pact-1.88.77-osx.tar.gz: Error: Error while installing binary: Checksum rejected for file 'pact-1.88.77-osx.tar.gz' with checksum pact-1.88.77-osx.tar.gz.checksum
  at throwError (xxx/node_modules/@pact-foundation/pact-node/standalone/install.js:42:11)
  at xxx/node_modules/@pact-foundation/pact-node/standalone/install.js:335:16
  at processTicksAndRejections 
```

**Comment by mefellows** [comment]
This usually means the downloaded binary was interfered with (e.g. a proxy) during download. If you check the file to see if it's a zip file or something else, that might help. 

The troubleshooting guide in the readme has some rules here.

**Comment by avinashs2401** [comment]
I'm unable to find the relevant troubleshooting guide. @mefellows Can you point me there?

**Comment by mefellows** [comment]
https://github.com/pact-foundation/pact-js/#troubleshooting--faqs

**Comment by avinashs2401** [comment]
The troubleshooting guide doesn't seem to have any hints on the checksum related issue. About the corporate proxy, yes I am using this behind a corporate proxy and I have the http_proxy and no_proxy directives correctly set.

**Comment by mefellows** [comment]
After an npm instnall, could you please check the contents of the standalone directory in the `@pact-foundation/pact_node` folder of `node_modules`? I'd like to see the type and size of the file mentioned .

e.g. `ls -larth node_modules/@pact-foundation/pact-node/standalone`

**Comment by avinashs2401** [comment]
There is no `pact-node` folder at all after the error from `npm install`

<img width="177" alt="Screenshot 2022-06-10 at 5 06 41 PM" src="https://user-images.githubusercontent.com/75415495/173056957-4ef1f206-cee0-482c-99fb-e0cfeea13459.png">

**Comment by mefellows** [comment]
Try installing it directly, just in case it's a dependency of one of the above (so it would be nested).

It does look like your proxy is getting in the way, is what I'm saying. My guess is that it's blocking the download from Github.

You will probably need to do https://github.com/pact-foundation/pact-js-core/tree/pact-node#skip-pact-binary-downloading then.

**Comment by mefellows** [comment]
Closing as the issue is stale.

NOTE: the latest version doesn't have this issue, as we don't download the binary at install time.
