### ISSUE TITLE
Can't install pact module when user npmrc exist on a folder without enough permission

### ISSUE THREAD

**Issue by shkedi** [pact-foundation/pact-js-core#384]
Use case:
As part of my CI installation, I installed pact inside docker, I got an error in the npm install

Investgation:
In my env, i have a node project that is Installed over a container. in the docker file, define the home project in the root folder (maybe a mistake) on the root folder (/root), and the project in the project folder (src/app). when doing npm install inside the container, the pact trying to read the user npmrc, that exists by default on the home folder, and it gets access denied.
On my side, the workaround for this is to change the root folder (home) permission or to change the home directory.

**Comment by mefellows** [comment]
I think probably this line needs to be guarded against: https://github.com/pact-foundation/pact-js-core/blob/1d63450f5d88f47d8f1e9345f97d761d5242a2de/standalone/install.ts#L13, or perhaps where it is used (e.g. https://github.com/pact-foundation/pact-js-core/blob/pact-node/standalone/install.ts#L154). If the `.npmrc` file cannot be found, we should just stick with the default behaviour.

**Comment by YOU54F** [comment]
> This module is not used anymore. npm config is parsed by npm itself and by @npmcli/config

I think we can remove that dependency completely, it's deprecated 

https://www.npmjs.com/package/libnpmconfig

**Comment by YOU54F** [comment]
the cli tools were moved into pact-js-cli and prepackaged so no download script was required to be called.

the code in question has been removed from both codebases, so this is no longer an issue :)
