### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by ghsouza89** [pact-foundation/pact-js-core#433]
_Thank you for reporting a bug! We appreciate it very much. Issues are a big input into the priorities for Pact development_

_All italic text in this template is safe to remove before submitting_

_Thanks again!_

### Software versions

_Please provide at least OS and version of pact-js_

- **OS**: _e.g. Windows 11 Home Single Language
- **Pact Node version**: 13.13.4
- **Node Version**: v14.18.0
- **Other Versions**: _Any other versions you think might be relevant (optional)_

### Issue Checklist

Please confirm the following:

- [X] I have upgraded to the latest
- [X] I have the read the FAQs in the Readme
- [ ] I have triple checked, that there are **no unhandled promises** in my code
- [ ] I have set my log level to debug and attached a log file showing the complete request/response cycle
- [ ] For bonus points and virtual high fives, I have created a reproduceable git repository (see below) to illustrate the problem

### Expected behaviour

_Provider Verification passed sucessfully_

### Actual behaviour

_TypeError: Cannot read property 'forEach' of undefined_

### Steps to reproduce

_Run the provider file_

`import { Verifier } from '@pact-foundation/pact';
import path from 'path';

describe('Pact Verification', () => {
  jest.setTimeout(50000);
  it('validates the expectations of dynamicApi Service', () => {
    const opts = {
      log: path.resolve(process.cwd(), 'logs', 'pact.log'),
      LogLevel: 'debug',
      providerBaseUrl: 'providerBaseUrl',
      pactBrokerUrl: 'pactBrokerUrl',
      pactBrokerToken: 'pactBrokerToken',
      pactUrls: [
        'pactUrls',
      ],
      publishVerificationResult: true,
      providerVersion: '2.0.0',
      provider: 'provider',
      tags: ['release'],
    };
    return new Verifier(opts).verifyProvider().then((output) => {
      console.log('Pact Verification Complete!');
      console.log(output);
    });
  });
});
`

_Here is the output_

`FAIL   contract-testing  apps/contract-testing/provider/dynamicApi.spec.ts
  Pact Verification
    × validates the expectations of dynamicApi Service (15 ms)

  ● Pact Verification › validates the expectations of dynamicApi Service

    TypeError: Cannot read property 'forEach' of undefined

      at ../../node_modules/@pact-foundation/pact-core/src/verifier/validateOptions.ts:266:15
          at Array.forEach (<anonymous>)
      at ../../node_modules/@pact-foundation/pact-core/src/verifier/validateOptions.ts:265:18
          at Array.forEach (<anonymous>)
      at validateOptions (../../node_modules/@pact-foundation/pact-core/src/verifier/validateOptions.ts:260:5)
      at new Verifier (../../node_modules/@pact-foundation/pact-core/src/verifier/index.ts:16:35)
      at Object.<anonymous>.exports.default (../../node_modules/@pact-foundation/pact-core/src/verifier/index.ts:30:56)
      at Pact.verifyPacts (../../node_modules/@pact-foundation/pact-core/src/pact.ts:158:27)
      at ../../node_modules/@pact-foundation/src/dsl/verifier/verifier.ts:137:29

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.036 s, estimated 3 s
Ran all test suites matching /apps\\contract-testing\\provider\\/i.`

![image](https://user-images.githubusercontent.com/104024271/223724257-41a33aec-fbd0-453f-b768-4095acc4a585.png)

_For extra bonus points and internet karma, provide a repository, gist or reproducible code snippet so that we can test the problem._

_We recommend forking the project and modifying a relevant example [in the examples folder](https://github.com/pact-foundation/pact-js/blob/master/examples)_

### Relevant log files

_Please ensure you set logging to `DEBUG` and attach any relevant log files here (or link to a gist)._

**Comment by ghsouza89** [comment]
PR related: https://github.com/pact-foundation/pact-js-core/pull/432

**Comment by mefellows** [comment]
Can you please re-test with the latest @ghsouza89? This should be fixed now. Thanks again for raising it.

**Comment by ghsouza89** [comment]
@mefellows here is the result after update the @pact-foundation/pact-core to 13.13.5

Before run I did the follow steps:

1. rm -rf node_modules
2. rm -f package-lock.json
3. npm cache clean --force
4. npm install

![image](https://user-images.githubusercontent.com/104024271/224743598-552038fb-41b6-4055-8fc7-006e00fbf041.png)

**Comment by TimothyJones** [comment]
`@pact-foundation/pact-core` is a dependency. You need to update `@pact-foundation/pact`

**Comment by TimothyJones** [comment]
You can do `npm ls @pact-foundation/pact-core` to see what you have

**Comment by ghsouza89** [comment]
> npm ls @pact-foundation/pact-core

here is the output:

`$ npm ls @pact-foundation/pact-core
themarkerr@1.4.0 C:\markerr-app
+-- @pact-foundation/pact@11.0.0
| `-- @pact-foundation/pact-core@13.13.4 
`-- @pact-foundation/pact-core@13.13.5 `


![image](https://user-images.githubusercontent.com/104024271/225014068-088f503e-2c0a-47a8-88a3-17f32dfba764.png)

**Comment by TimothyJones** [comment]
This illustrates the problem. You need to bump the version of @pact-foundation/pact to the latest (and remove the other pact-core dependency, you don't need to depend on it directly). The latest is 11.0.2, although I believe this was fixed in 11.0.1.

Apologies for not being clear about this the first time.

**Comment by ghsouza89** [comment]
> This illustrates the problem. You need to bump the version of @pact-foundation/pact to the latest (and remove the other pact-core dependency, you don't need to depend on it directly). The latest is 11.0.2, although I believe this was fixed in 11.0.1.
> 
> Apologies for not being clear about this the first time.

worked @TimothyJones , thanks a lot for your support, let doc all those steps!
