### ISSUE TITLE
Binary Content Matching is odd - cross platform/arch

### ISSUE THREAD

**Issue by YOU54F** [pact-foundation/pact-js-core#447]
## Smells

Cross CI provider and cross arch has shown a few inconsistencies in content-type matching, which is clearly demonstrable here. Haven't thought of a solution just yet, but this at least highlights and allows us to test more combinations than before

Encountered in https://github.com/pact-foundation/pact-js-core/pull/444#issue-1692947149

If you have code that looks like this, there is a definite code-smell

https://github.com/pact-foundation/pact-js-core/blob/facfef810036d0b80fb3c2fbcafd8efa255b6171/test/consumer.integration.spec.ts#L23-L34

The condition is used in these tests

https://github.com/pact-foundation/pact-js-core/blob/dac0e46eafc5cdf633f459adc591e9cc5ba26c24/test/consumer.integration.spec.ts#L77-L87

https://github.com/pact-foundation/pact-js-core/blob/dac0e46eafc5cdf633f459adc591e9cc5ba26c24/test/message.integration.spec.ts#L94-L109

>  See https://github.com/pact-foundation/pact-reference/issues/171 for why we have an OS switch here
    Windows: does not have magic mime matcher, uses content-type
    OSX on CI: does not magic mime matcher, uses content-type
    OSX: has magic mime matcher, sniffs content
     Linux: has magic mime matcher, sniffs content
 
 So based on our compat table of 
 
 | OS                     | Amd64 | Arm64 |
|--------------- |---------|-----|
| Linux (glibc)    | ✅          | ✅   |
| Mac                  | ✅          | ✅  |
| Windows          | ✅          | ❌   | 
| Linux (alpine)  | ❌          | ❌ | 

✅ = supported
❌ = not supported

We have a few different ways we can test to cover different arch combinations

- Locally
- Locally with GitHub Actions / Act
- GitHub Actions
- Locally with Cirrus CLI
- Cirrus CI
     
| OS                     | Amd64 | Arm64 |   Amd64 (GH) | Amd64 (GH Act) | Amd64 (Cirrus) | Arm64 (Cirrus CI) |    Amd64 (Cirrus CLI) | Arm64 (Cirrus CLI) |  
|--------------- |---------|-----|-----|-----|-----|-----|-----|-----|
| Linux (glibc)    | ❓         | ❓   |❓   |❓   |❓   |❓   |❓   |❓   |
| Mac                  | ❓          | ❓  |❓   |❌   |❓   |❓   |❓   |❓   |
| Windows          | ❓         | ❌   | ❓   |❌   |❓   |❌   |❓   |❌   |
| Linux (alpine)  | ❌          | ❌ | ❌|❌|❌|❌|❌|❌|

❓ = needs test evidence
❌ = not supported, or untestable on platform

**Comment by damusix** [comment]
@YOU54F Running into a similar issue on Mac Arm64:

```
error @pact-foundation/pact-node@8.6.2: The CPU architecture "arm64" is incompatible with this module.
error Found incompatible module.
```

**Comment by YOU54F** [comment]
hi this isnt the same issue, you are running an old version of pact-node which has never supported arm64

**Comment by YOU54F** [comment]
you can run pact-node with rosetta or vote on this issue to bring native arm support to pact-node

or migrate to pact-js-core which supports arm64 on macos and linux

**Comment by YOU54F** [comment]
fyi this related issue is where rosetta was supported for pact-node on macos

https://github.com/pact-foundation/pact-js-core/issues/264

youll need a version bump to 10.x as described in the linked issue to get it working with rosetta
👍🏽

**Comment by damusix** [comment]
@YOU54F Thank you sir, let me look into this

**Comment by YOU54F** [comment]
So it appears installing `shared-mime-info` in arm64 containers will result in the same behaviour on Linux

## Debian

```
apt install shared-mime-info
```

## Alpine

``` 
apk add shared-mime-info
```

**Comment by YOU54F** [comment]
Fixed as part of https://github.com/pact-foundation/pact-reference/pull/429

will be sorted in 0.4.21 release of the pact_ffi which can then be consumed in here

**Comment by YOU54F** [comment]
Fixed in 

- Pact-JS-Core from [v15.0.0](https://github.com/pact-foundation/pact-js-core/releases/tag/v15.1.0)
- Pact-Core from from [v13.0.0](https://github.com/pact-foundation/pact-js/releases/tag/v13.1.0)
