### ISSUE TITLE
The issue is we are not able to download as we need to provide credentials to access the path due to that download getting failed

### ISSUE THREAD

**Issue by venkatesh-civic** [pact-foundation/pact-js-core#464]
We are using pact behind a corporate firewall. we have the following pact-related entries in our package.json:

  "config": {
    "pact_binary_location": "https://artifactory.ourcompany.com.au/artifactory/pact-github-repo/download/v1.88.81/"
  },
...
  "devDependencies": {
"@pact-foundation/pact": "9.9.2",
    "@pact-foundation/pact-node": "10.17.1"
}

Installing Pact Standalone Binary for linux.
Downloading Pact Standalone Binary v1.88.81 for platform linux from https://artifactory.global.xx.com/artifactory/ui/pact-1.88.81-linux-x86_64.tar.gz
Please note: we are tracking this download anonymously to gather important usage statistics. To disable tracking, set 'pact_do_not_track: true' in your package.json 'config' section.
****
**The issue is we are not able to download as we need to provide credentials to access the path due to that download getting failed, is there fix for the same ?**

**Is there way without binary can we acheive?**

**Comment by YOU54F** [comment]
please update to the latest version where pact binaries are pre-baked into the npm packge.

You are are using a 3 year old package of pact-js and a 2 year old package of pact-js
