### ISSUE TITLE
PACT CRASHED

### ISSUE THREAD

**Issue by uttam-gelot** [pact-foundation/pact-js-core#524]
### Software versions

- **OS**: _Ubuntu_
- **@pact-foundation/pact**: _10.4.0_
- **Node Version**: _20.14.0_
- **nestjs-pact**: _2.3.1_

#### Some more information
- I'm using NestJS version: _10.4.1_
- I'm using `nestjs-pact` library with version: _2.3.1_
- all the test cases are failing due to failed verification.
- I'm facing issue when I upgraded versions of `nestjs-pact` from _v2.2.1_ to _v.2.3.1_ and `@pact-foundation/pact` from _v.9.18.1_ to _v.10.4.0_

I'm getting below errors:
![image](https://github.com/user-attachments/assets/e98e9c7b-3deb-45b3-9fbf-c134cb91d874)
![image](https://github.com/user-attachments/assets/99cdb971-938d-4139-a136-2eeb895547cc)
![image](https://github.com/user-attachments/assets/c966a762-81a3-4aed-ab41-8b92a651fecc)

**Comment by uttam-gelot** [comment]
@mefellows @YOU54F could you please look into it?

**Comment by mefellows** [comment]
Please provide a repro

**Comment by uttam-gelot** [comment]
> Please provide a repro

@mefellows I've large codebase in which this issue is occurring. creating repository will take time. in the message it mentioned to report so I reported it.

**Comment by mefellows** [comment]
Thanks, we don't need your actual code just some code that reproduces the error. The migration from 9-10 was a significant change.

P.a. you need not tag maintainers, we already subscribe to all issues.

**Comment by uttam-gelot** [comment]
Got it. I'm trying to create repo. I'll share here once ready.

> P.a. you need not tag maintainers, we already subscribe to all issues.

Okay. thank you.

**Comment by YOU54F** [comment]
>_For extra bonus points and internet karma, provide a repository, gist or reproducible code snippet so that we can test the problem._

☝🏾 in the new issue template

I'll be honest and say nestjs-pact has stalled in terms of development, and I'm personally spread over too many things to be massively driven to do anything about it, so we would either ask for contributions to fix it, or suggest migrating to using pact-js directly.

**Comment by uttam-gelot** [comment]
creating repo will take time for me maybe I can do it over weekend but for now I've created [Gist](https://gist.github.com/uttam-gelot/550e1aee93cbef64b45055ec596419a5). Let me know if you need anything else.

**Comment by YOU54F** [comment]
I added some previous examples

https://github.com/YOU54F/nestjs-pact-test?tab=readme-ov-file#pact-js-v10

off the back of 

https://github.com/pact-foundation/pact-js/issues/863

**Comment by uttam-gelot** [comment]
this one was helpful. thank you @YOU54F

**Comment by mefellows** [comment]
Thanks Yousaf!

**Comment by uttam-gelot** [comment]
I removed `nestjs-pact` and using `jest-pact`.

**Comment by JP-Ellis** [comment]
> I removed `nestjs-pact` and using `jest-pact`.

Does this mean you issue is fixed? If so, this ticket can be closed.

**Comment by uttam-gelot** [comment]
Yes, it's working. I'm closing it thank you everyone.
